import type { FormEvent } from "react";
import { Save } from "lucide-react";
import { FormField } from "@/components/FormField";
import { Button } from "@/components/ui/button";
import { Dialog, DialogBody, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/AppDialog";
import { Input } from "@/components/ui/input";
import type { CompanyUpdateInput } from "@/types";

export function CompanyEditDialog({ open, form, errors, busy, onOpenChange, onSubmit, onChange, onValidate, onCancel }: { open: boolean; form: CompanyUpdateInput | null; errors: Record<string, string>; busy: boolean; onOpenChange: (open: boolean) => void; onSubmit: (event: FormEvent) => void; onChange: (form: CompanyUpdateInput) => void; onValidate: (field: "name" | "slug" | "contact_email", value: string) => void; onCancel: () => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent>{form && <form onSubmit={onSubmit} noValidate><DialogHeader><DialogTitle>编辑公司资料</DialogTitle><DialogDescription>更新后的公司资料会同步显示在后台工作台。</DialogDescription></DialogHeader><DialogBody><FormField label="公司名称" htmlFor="company-name" required error={errors.name}><Input id="company-name" value={form.name} onChange={(event) => { const value = event.target.value; onChange({ ...form, name: value }); onValidate("name", value); }} placeholder="请输入公司名称" aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? "company-name-error" : undefined} /></FormField><FormField label="公司简称" htmlFor="company-slug" required error={errors.slug} className="mt-4"><Input id="company-slug" value={form.slug} onChange={(event) => { const value = event.target.value.toLowerCase(); onChange({ ...form, slug: value }); onValidate("slug", value); }} placeholder="请输入公司简称" aria-invalid={Boolean(errors.slug)} aria-describedby={errors.slug ? "company-slug-error" : undefined} /></FormField><FormField label="联系邮箱" htmlFor="company-contact-email" error={errors.contact_email} className="mt-4"><Input id="company-contact-email" type="email" value={form.contact_email ?? ""} onChange={(event) => { const value = event.target.value; onChange({ ...form, contact_email: value || null }); onValidate("contact_email", value); }} placeholder="请输入联系邮箱" aria-invalid={Boolean(errors.contact_email)} aria-describedby={errors.contact_email ? "company-contact-email-error" : undefined} /></FormField></DialogBody><DialogFooter className="mt-6"><Button type="button" variant="outline" onClick={onCancel} disabled={busy}>取消</Button><Button type="submit" disabled={busy}><Save />保存公司资料</Button></DialogFooter></form>}</DialogContent></Dialog>;
}
