"""增加 Agent 与模型端点控制面，并回填历史会话。

Revision ID: 8f4d8fe16359
Revises: 20260903_0002
Create Date: 2026-09-04 11:00:45.299214
"""

import hashlib
import json
from collections.abc import Sequence
from uuid import NAMESPACE_URL, UUID, uuid5

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8f4d8fe16359"
down_revision: str | None = "20260903_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS supportops_checkpoints")
    op.create_table(
        "model_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("encrypted_secret", sa.Text(), nullable=False),
        sa.Column("masked_hint", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["endpoint_id"], ["model_endpoints.id"], use_alter=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "endpoint_id"),
    )
    op.create_index(
        op.f("ix_model_credentials_endpoint_id"), "model_credentials", ["endpoint_id"], unique=False
    )
    op.create_index(
        op.f("ix_model_credentials_tenant_id"), "model_credentials", ["tenant_id"], unique=False
    )
    op.create_table(
        "model_credential_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("encrypted_secret", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["credential_id"], ["model_credentials.id"]),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id", "revision"),
    )
    op.create_index(
        op.f("ix_model_credential_revisions_credential_id"),
        "model_credential_revisions",
        ["credential_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_credential_revisions_tenant_id"),
        "model_credential_revisions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("logo_url", sa.String(length=2000), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("welcome_message", sa.String(length=2000), nullable=False),
        sa.Column(
            "suggested_prompts",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "ACTIVE", "DISABLED", name="agentstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("read_only", sa.Boolean(), nullable=False),
        sa.Column("active_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["active_version_id"], ["agent_versions.id"], use_alter=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug"),
    )
    op.create_index(op.f("ix_agents_status"), "agents", ["status"], unique=False)
    op.create_index(op.f("ix_agents_tenant_id"), "agents", ["tenant_id"], unique=False)
    op.create_table(
        "model_endpoints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("logo_url", sa.String(length=2000), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "DISABLED",
                name="modelendpointstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("read_only", sa.Boolean(), nullable=False),
        sa.Column("active_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_version_id"], ["model_endpoint_versions.id"], use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name"),
    )
    op.create_index(op.f("ix_model_endpoints_status"), "model_endpoints", ["status"], unique=False)
    op.create_index(
        op.f("ix_model_endpoints_tenant_id"), "model_endpoints", ["tenant_id"], unique=False
    )
    op.create_table(
        "agent_access_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "subject_type",
            sa.Enum("USER", "ROLE", name="grantsubjecttype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("subject_id", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(subject_id) > 0", name="ck_agent_grant_subject_id"),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "subject_type", "subject_id"),
    )
    op.create_index(
        op.f("ix_agent_access_grants_agent_id"), "agent_access_grants", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_access_grants_tenant_id"), "agent_access_grants", ["tenant_id"], unique=False
    )
    op.create_table(
        "agent_audit_events",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resource_type",
            sa.Enum(
                "AGENT", "MODEL_ENDPOINT", name="auditresourcetype", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("model_endpoint_id", sa.Uuid(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "CREATED",
                "PROFILE_UPDATED",
                "DRAFT_UPDATED",
                "VALIDATION_FAILED",
                "VERSION_PUBLISHED",
                "VERSION_ACTIVATED",
                "VERSION_ROLLED_BACK",
                "DISABLED",
                "GRANTS_REPLACED",
                "CREDENTIAL_ROTATED",
                "CONNECTION_TESTED",
                name="auditaction",
                native_enum=False,
                length=64,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_endpoint_id"],
            ["model_endpoints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_audit_events_correlation_id"),
        "agent_audit_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_audit_events_tenant_id"), "agent_audit_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "agent_drafts",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_index(op.f("ix_agent_drafts_tenant_id"), "agent_drafts", ["tenant_id"], unique=False)
    op.create_table(
        "model_endpoint_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "provider_kind",
            sa.Enum(
                "OPENAI_OFFICIAL",
                "OPENAI_COMPATIBLE",
                name="modelproviderkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "api_protocol",
            sa.Enum(
                "RESPONSES",
                "CHAT_COMPLETIONS",
                name="modelapiprotocol",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.String(length=2000), nullable=False),
        sa.Column("remote_model_name", sa.String(length=300), nullable=False),
        sa.Column(
            "capabilities",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "defaults",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "request_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "pricing",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("credential_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum(
                "UNTESTED",
                "VERIFIED",
                "PARTIAL",
                "FAILED",
                name="modelverificationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "verification_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["model_credentials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["model_endpoints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint_id", "version_number"),
    )
    op.create_index(
        op.f("ix_model_endpoint_versions_credential_id"),
        "model_endpoint_versions",
        ["credential_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_endpoint_versions_endpoint_id"),
        "model_endpoint_versions",
        ["endpoint_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_endpoint_versions_tenant_id"),
        "model_endpoint_versions",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "agent_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("config_digest", sa.String(length=64), nullable=False),
        sa.Column("model_endpoint_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "resolved_tool_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("release_notes", sa.String(length=2000), nullable=False),
        sa.Column("published_by", sa.Uuid(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_endpoint_version_id"],
            ["model_endpoint_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["published_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "version_number"),
    )
    op.create_index(
        op.f("ix_agent_versions_agent_id"), "agent_versions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_versions_model_endpoint_version_id"),
        "agent_versions",
        ["model_endpoint_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_versions_tenant_id"), "agent_versions", ["tenant_id"], unique=False
    )
    op.create_foreign_key(
        "fk_model_credentials_endpoint_id",
        "model_credentials",
        "model_endpoints",
        ["endpoint_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_model_endpoints_active_version_id",
        "model_endpoints",
        "model_endpoint_versions",
        ["active_version_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_agents_active_version_id",
        "agents",
        "agent_versions",
        ["active_version_id"],
        ["id"],
    )
    op.add_column("agent_runs", sa.Column("agent_id", sa.Uuid(), nullable=True))
    op.add_column("agent_runs", sa.Column("agent_version_id", sa.Uuid(), nullable=True))
    op.add_column("agent_runs", sa.Column("model_endpoint_version_id", sa.Uuid(), nullable=True))
    op.add_column("agent_runs", sa.Column("credential_revision", sa.Integer(), nullable=True))
    op.add_column("agent_runs", sa.Column("config_digest", sa.String(length=64), nullable=True))
    op.add_column(
        "agent_runs",
        sa.Column(
            "identity_roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_agent_runs_agent_id"), "agent_runs", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_agent_runs_agent_version_id"), "agent_runs", ["agent_version_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_runs_model_endpoint_version_id"),
        "agent_runs",
        ["model_endpoint_version_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_agent_runs_agent_version_id",
        "agent_runs",
        "agent_versions",
        ["agent_version_id"],
        ["id"],
    )
    op.create_foreign_key(
        "fk_agent_runs_model_endpoint_version_id",
        "agent_runs",
        "model_endpoint_versions",
        ["model_endpoint_version_id"],
        ["id"],
    )
    op.create_foreign_key("fk_agent_runs_agent_id", "agent_runs", "agents", ["agent_id"], ["id"])
    op.add_column("conversations", sa.Column("agent_id", sa.Uuid(), nullable=True))
    op.add_column("conversations", sa.Column("agent_version_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_conversations_agent_id"), "conversations", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_conversations_agent_version_id"),
        "conversations",
        ["agent_version_id"],
        unique=False,
    )
    op.create_index(
        "ix_conversations_tenant_user_agent_updated",
        "conversations",
        ["tenant_id", "user_id", "agent_id", "updated_at"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_conversations_agent_id", "conversations", "agents", ["agent_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_conversations_agent_version_id",
        "conversations",
        "agent_versions",
        ["agent_version_id"],
        ["id"],
    )
    _backfill_historical_conversations()
    op.alter_column("conversations", "agent_id", nullable=False)
    op.alter_column("conversations", "agent_version_id", nullable=False)
    op.alter_column("agent_runs", "agent_id", nullable=False)
    op.alter_column("agent_runs", "agent_version_id", nullable=False)
    op.alter_column("agent_runs", "model_endpoint_version_id", nullable=False)
    op.alter_column("agent_runs", "credential_revision", nullable=False)
    op.alter_column("agent_runs", "config_digest", nullable=False)
    op.execute(
        "UPDATE agent_runs SET identity_roles = users.roles "
        "FROM conversations, users "
        "WHERE agent_runs.conversation_id = conversations.id "
        "AND conversations.user_id = users.id AND agent_runs.identity_roles IS NULL"
    )
    op.alter_column("agent_runs", "identity_roles", nullable=False)
    # ### end Alembic commands ###


def _stable_id(tenant_id: UUID, resource: str) -> UUID:
    return uuid5(NAMESPACE_URL, f"supportops:{tenant_id}:migration:{resource}")


def _backfill_historical_conversations() -> None:
    connection = op.get_bind()
    tenant_rows = connection.execute(
        sa.text("SELECT DISTINCT tenant_id FROM conversations WHERE agent_id IS NULL")
    ).all()
    for row in tenant_rows:
        tenant_id = UUID(str(row.tenant_id))
        creator_id = connection.execute(
            sa.text(
                "SELECT id FROM users WHERE tenant_id = :tenant_id ORDER BY created_at, id LIMIT 1"
            ),
            {"tenant_id": tenant_id},
        ).scalar_one()
        endpoint_id = _stable_id(tenant_id, "model-endpoint")
        credential_id = _stable_id(tenant_id, "model-credential")
        model_version_id = _stable_id(tenant_id, "model-version")
        agent_id = _stable_id(tenant_id, "agent")
        agent_version_id = _stable_id(tenant_id, "agent-version")
        config = {
            "schema_version": "2",
            "prompt": {"system_prompt": "只读历史迁移 Agent，不允许创建新的消息或运行。"},
            "model": {
                "model_endpoint_id": str(endpoint_id),
                "fallback_model_endpoint_ids": [],
                "generation": {
                    "temperature": 0.2,
                    "max_output_tokens": 4096,
                    "timeout_seconds": 60,
                    "max_retries": 0,
                },
            },
            "tools": [],
            "runtime": {
                "engine": "langchain_create_agent_v1",
                "context_schema": "support_context_v1",
                "response_schema": "support_answer_v1",
                "response_strategy": "tool",
                "checkpointer": "postgres",
                "model_call_limit": 1,
                "tool_call_limit": 1,
                "run_timeout_seconds": 10,
                "max_parallel_tools": 1,
                "max_input_tokens": None,
                "max_cost_usd": None,
            },
            "knowledge": {"knowledge_base_ids": []},
            "memory": {"long_term_policy_id": None},
        }
        config_json = json.dumps(config, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        config_digest = hashlib.sha256(config_json.encode()).hexdigest()
        common = {"tenant_id": tenant_id, "creator_id": creator_id}
        connection.execute(
            sa.text(
                "INSERT INTO model_endpoints "
                "(id, tenant_id, name, logo_url, status, read_only, active_version_id, created_by, "
                "updated_by, created_at, updated_at) VALUES "
                "(:id, :tenant_id, '历史迁移模型（只读）', NULL, 'DISABLED', TRUE, NULL, "
                ":creator_id, :creator_id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ),
            {**common, "id": endpoint_id},
        )
        connection.execute(
            sa.text(
                "INSERT INTO model_credentials "
                "(id, tenant_id, endpoint_id, provider, encrypted_secret, masked_hint, "
                "revision, created_at, rotated_at) VALUES "
                "(:id, :tenant_id, :endpoint_id, 'migration', 'unavailable', '不可用', 1, "
                "CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ),
            {**common, "id": credential_id, "endpoint_id": endpoint_id},
        )
        connection.execute(
            sa.text(
                "INSERT INTO model_credential_revisions "
                "(id, tenant_id, credential_id, revision, encrypted_secret, created_at) "
                "VALUES (:id, :tenant_id, :credential_id, 1, 'unavailable', CURRENT_TIMESTAMP)"
            ),
            {
                "id": _stable_id(tenant_id, "model-credential-revision-1"),
                "tenant_id": tenant_id,
                "credential_id": credential_id,
            },
        )
        connection.execute(
            sa.text(
                "INSERT INTO model_endpoint_versions "
                "(id, tenant_id, endpoint_id, version_number, provider_kind, api_protocol, "
                "base_url, remote_model_name, capabilities, defaults, request_metadata, "
                "pricing, credential_id, verification_status, verification_result, "
                "verified_at, created_by, created_at) VALUES "
                "(:id, :tenant_id, :endpoint_id, 1, 'OPENAI_COMPATIBLE', "
                "'CHAT_COMPLETIONS', 'https://migration.invalid/v1', 'unavailable', "
                "CAST(:empty AS jsonb), CAST(:empty AS jsonb), CAST(:empty AS jsonb), "
                "CAST(:empty AS jsonb), :credential_id, 'UNTESTED', CAST(:empty AS jsonb), "
                "NULL, :creator_id, CURRENT_TIMESTAMP)"
            ),
            {
                **common,
                "id": model_version_id,
                "endpoint_id": endpoint_id,
                "credential_id": credential_id,
                "empty": "{}",
            },
        )
        connection.execute(
            sa.text("UPDATE model_endpoints SET active_version_id = :version_id WHERE id = :id"),
            {"version_id": model_version_id, "id": endpoint_id},
        )
        connection.execute(
            sa.text(
                "INSERT INTO agents "
                "(id, tenant_id, slug, name, logo_url, description, welcome_message, "
                "suggested_prompts, status, read_only, active_version_id, created_by, updated_by, "
                "created_at, updated_at) VALUES "
                "(:id, :tenant_id, 'supportops-migrated', '历史会话（只读）', NULL, "
                "'用于保留升级前会话，不接受新消息。', '', CAST(:prompts AS jsonb), "
                "'DISABLED', TRUE, NULL, :creator_id, :creator_id, "
                "CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ),
            {**common, "id": agent_id, "prompts": "[]"},
        )
        connection.execute(
            sa.text(
                "INSERT INTO agent_drafts "
                "(agent_id, tenant_id, revision, schema_version, config, updated_by, updated_at) "
                "VALUES (:agent_id, :tenant_id, 1, '2', CAST(:config AS jsonb), :creator_id, "
                "CURRENT_TIMESTAMP)"
            ),
            {**common, "agent_id": agent_id, "config": config_json},
        )
        connection.execute(
            sa.text(
                "INSERT INTO agent_versions "
                "(id, tenant_id, agent_id, version_number, schema_version, config, "
                "config_digest, model_endpoint_version_id, resolved_tool_ids, release_notes, "
                "published_by, published_at) VALUES "
                "(:id, :tenant_id, :agent_id, 1, '2', CAST(:config AS jsonb), :digest, "
                ":model_version_id, CAST(:tools AS jsonb), '自动迁移历史数据', :creator_id, "
                "CURRENT_TIMESTAMP)"
            ),
            {
                **common,
                "id": agent_version_id,
                "agent_id": agent_id,
                "config": config_json,
                "digest": config_digest,
                "model_version_id": model_version_id,
                "tools": "[]",
            },
        )
        connection.execute(
            sa.text("UPDATE agents SET active_version_id = :version_id WHERE id = :id"),
            {"version_id": agent_version_id, "id": agent_id},
        )
        connection.execute(
            sa.text(
                "UPDATE conversations SET agent_id = :agent_id, "
                "agent_version_id = :agent_version_id "
                "WHERE tenant_id = :tenant_id AND agent_id IS NULL"
            ),
            {
                "tenant_id": tenant_id,
                "agent_id": agent_id,
                "agent_version_id": agent_version_id,
            },
        )
        connection.execute(
            sa.text(
                "UPDATE agent_runs SET agent_id = :agent_id, "
                "agent_version_id = :agent_version_id, "
                "model_endpoint_version_id = :model_version_id, credential_revision = 1, "
                "config_digest = :digest WHERE tenant_id = :tenant_id AND agent_id IS NULL"
            ),
            {
                "tenant_id": tenant_id,
                "agent_id": agent_id,
                "agent_version_id": agent_version_id,
                "model_version_id": model_version_id,
                "digest": config_digest,
            },
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SCHEMA IF EXISTS supportops_checkpoints CASCADE")
    op.execute("ALTER TABLE agents DROP CONSTRAINT IF EXISTS fk_agents_active_version_id")
    op.execute(
        "ALTER TABLE model_endpoints DROP CONSTRAINT IF EXISTS fk_model_endpoints_active_version_id"
    )
    op.execute(
        "ALTER TABLE model_credentials DROP CONSTRAINT IF EXISTS fk_model_credentials_endpoint_id"
    )
    op.drop_constraint("fk_conversations_agent_version_id", "conversations", type_="foreignkey")
    op.drop_constraint("fk_conversations_agent_id", "conversations", type_="foreignkey")
    op.drop_index("ix_conversations_tenant_user_agent_updated", table_name="conversations")
    op.drop_index(op.f("ix_conversations_agent_version_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_agent_id"), table_name="conversations")
    op.drop_column("conversations", "agent_version_id")
    op.drop_column("conversations", "agent_id")
    op.drop_constraint("fk_agent_runs_model_endpoint_version_id", "agent_runs", type_="foreignkey")
    op.drop_constraint("fk_agent_runs_agent_version_id", "agent_runs", type_="foreignkey")
    op.drop_constraint("fk_agent_runs_agent_id", "agent_runs", type_="foreignkey")
    op.drop_index(op.f("ix_agent_runs_model_endpoint_version_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_agent_version_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_agent_id"), table_name="agent_runs")
    op.drop_column("agent_runs", "config_digest")
    op.drop_column("agent_runs", "identity_roles")
    op.drop_column("agent_runs", "credential_revision")
    op.drop_column("agent_runs", "model_endpoint_version_id")
    op.drop_column("agent_runs", "agent_version_id")
    op.drop_column("agent_runs", "agent_id")
    op.drop_index(op.f("ix_agent_versions_tenant_id"), table_name="agent_versions")
    op.drop_index(op.f("ix_agent_versions_model_endpoint_version_id"), table_name="agent_versions")
    op.drop_index(op.f("ix_agent_versions_agent_id"), table_name="agent_versions")
    op.drop_table("agent_versions")
    op.drop_index(
        op.f("ix_model_endpoint_versions_tenant_id"), table_name="model_endpoint_versions"
    )
    op.drop_index(
        op.f("ix_model_endpoint_versions_endpoint_id"), table_name="model_endpoint_versions"
    )
    op.drop_index(
        op.f("ix_model_endpoint_versions_credential_id"), table_name="model_endpoint_versions"
    )
    op.drop_table("model_endpoint_versions")
    op.drop_index(op.f("ix_agent_drafts_tenant_id"), table_name="agent_drafts")
    op.drop_table("agent_drafts")
    op.drop_index(op.f("ix_agent_audit_events_tenant_id"), table_name="agent_audit_events")
    op.drop_index(op.f("ix_agent_audit_events_correlation_id"), table_name="agent_audit_events")
    op.drop_table("agent_audit_events")
    op.drop_index(op.f("ix_agent_access_grants_tenant_id"), table_name="agent_access_grants")
    op.drop_index(op.f("ix_agent_access_grants_agent_id"), table_name="agent_access_grants")
    op.drop_table("agent_access_grants")
    op.drop_index(op.f("ix_model_endpoints_tenant_id"), table_name="model_endpoints")
    op.drop_index(op.f("ix_model_endpoints_status"), table_name="model_endpoints")
    op.drop_table("model_endpoints")
    op.drop_index(op.f("ix_agents_tenant_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_status"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_model_credentials_tenant_id"), table_name="model_credentials")
    op.drop_index(op.f("ix_model_credentials_endpoint_id"), table_name="model_credentials")
    op.execute("DROP TABLE IF EXISTS model_credential_revisions")
    op.drop_table("model_credentials")
    # ### end Alembic commands ###
