import type { FormEvent } from "react";
import { FormField } from "@/components/FormField";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { ModelEndpoint, ModelEndpointModel } from "@/types";

export type ActiveModelOption = { endpoint: ModelEndpoint; model: ModelEndpointModel };

/** 新建 Agent 草稿弹窗。 */
export function CreateAgentDialog({ open, busy, name, slug, description, prompt, selectedModelId, models, errors, onOpenChange, onSubmit, onNameChange, onSlugChange, onDescriptionChange, onPromptChange, onModelChange, onValidate, onCancel }: { open: boolean; busy: boolean; name: string; slug: string; description: string; prompt: string; selectedModelId: string; models: ActiveModelOption[]; errors: Record<string, string>; onOpenChange: (open: boolean) => void; onSubmit: (event: FormEvent) => void; onNameChange: (value: string) => void; onSlugChange: (value: string) => void; onDescriptionChange: (value: string) => void; onPromptChange: (value: string) => void; onModelChange: (option: ActiveModelOption) => void; onValidate: (field: "name" | "slug" | "prompt" | "model", value: string) => void; onCancel: () => void }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto"><form onSubmit={onSubmit} noValidate><DialogHeader><DialogTitle>新建 Agent 草稿</DialogTitle><DialogDescription>先创建基础草稿，之后可继续配置模型、工具、权限和发布版本。</DialogDescription></DialogHeader><FormField label="名称" htmlFor="create-agent-name" required error={errors.name} className="mt-5"><Input id="create-agent-name" value={name} onChange={(event) => onNameChange(event.target.value)} onBlur={(event) => onValidate("name", event.currentTarget.value)} placeholder="请输入 Agent 名称" aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? "create-agent-name-error" : undefined} /></FormField><FormField label="Slug" htmlFor="create-agent-slug" required error={errors.slug} className="mt-4"><Input id="create-agent-slug" value={slug} onChange={(event) => onSlugChange(event.target.value)} onBlur={(event) => onValidate("slug", event.currentTarget.value)} placeholder="请输入 Agent Slug" aria-invalid={Boolean(errors.slug)} aria-describedby={errors.slug ? "create-agent-slug-error" : undefined} /></FormField><Label className="mt-4 block text-sm">描述<Input className="mt-2" value={description} onChange={(event) => onDescriptionChange(event.target.value)} placeholder="请输入 Agent 描述" /></Label><FormField label="模型" htmlFor="create-agent-model" required error={errors.model} className="mt-4"><Select value={selectedModelId || undefined} onValueChange={(value) => { const option = models.find((item) => item.model.id === value); if (option) onModelChange(option); }}><SelectTrigger id="create-agent-model" className="w-full" aria-invalid={Boolean(errors.model)} aria-describedby={errors.model ? "create-agent-model-error" : undefined}><SelectValue placeholder="选择已验证模型" /></SelectTrigger><SelectContent>{models.map(({ endpoint, model }) => <SelectItem key={model.id} value={model.id}>{endpoint.name} / {model.display_name || model.upstream_model_id}</SelectItem>)}</SelectContent></Select></FormField><FormField label="System Prompt" htmlFor="create-agent-prompt" required error={errors.prompt} className="mt-4"><Textarea id="create-agent-prompt" className="min-h-32" value={prompt} onChange={(event) => onPromptChange(event.target.value)} onBlur={(event) => onValidate("prompt", event.currentTarget.value)} placeholder="请输入 System Prompt" aria-invalid={Boolean(errors.prompt)} aria-describedby={errors.prompt ? "create-agent-prompt-error" : undefined} /></FormField><DialogFooter className="mt-6"><Button type="button" variant="outline" onClick={onCancel} disabled={busy}>取消</Button><Button type="submit" disabled={busy || models.length === 0}>{busy ? "创建中…" : "创建 Agent 草稿"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
